apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::466847355032:role/czhang
      username: cluster-admin
      groups:
        - system:masters
