apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:sts::466847355032:assumed-role/AWSReservedSSO_RS-DEVOPS_3cddbd8a038b57ac/czhang
      username: czhang
      groups:
        - system:masters
        
