apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::466847355032:role/AWSReservedSSO_RS-DEVOPS_3cddbd8a038b57ac
      username: czhang
      groups:
        - system:masters
    - rolearn: arn:aws:iam:466847355032:role/bottlerocket-eks-node-group-20240514130810459800000004
      username: system:node:ip-10-0-102-58.eu-west-2.compute.internal
      groups:
        - system:bootstrappers
        - system:nodes
